name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Test and Build Web
    env:
      my_secret: ${{secrets.COMMIT_SECRET}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release --base-href /fractter/
      - run: |
          cd build/web
          git init
          git config --global user.email werainkhatri.work@gmail.com
          git config --global user.name werainkhatri
          git remote add origin https://${{secrets.COMMIT_SECRET}}@github.com/werainkhatri/fractter.git
          git checkout -b web
          git add --all
          git commit -m "build: web"
          git push origin web -f
